before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
release:
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    name: toker
    description: Simple token management tool
    homepage: https://github.com/YaleSpinup/toker
    tap:
      owner: yalespinup
      name: homebrew-tools
    install: |
      bin.install "toker"
    license: AGPL-3.0-or-later
    folder: Formula
    test: |
      system "#{bin}/toker", "version"
